name: Windows MSBuild

on:
  push:
    branches: [ main ]        
  pull_request:
    branches: [ main ]
  workflow_dispatch:         

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build x64 Release
        run: msbuild .\Chess.sln /m /p:Configuration=Release /p:Platform=x64